### ISSUE TITLE
FE 코드 피드백

### ISSUE THREAD

**Issue by crongro** [softeerbootcamp/Team8_FullStack#149]
**api/index.js** 
URL은 설정파일로 분리할 수 있으면 그렇게 해보세요.
용도에 맞게 여러가지 request 함수 나눈 것이 좋네요.

**login.vue**
async 함수안에서 await 를 사용했으면 들여쓰기를 없애는 방향이 더 좋아요.
await foo().then() 하지말고
이런식으로 then대신 await를 활용하세요.
```
const useData = await foo();
await bar(usreData);
```

**view/*.vue**
- 통신과정의 에러처리 시도한것 좋고 좀더 디테일하게 에러상황에 대처하는 코드를 구현해보세요.
서버에서 어떤 응답을 받아서 클라이언트에서 그 경우를 따져서 try/catch로 보내서 렌더링을 한다던가.
- /view 디렉토리 아래 파일이 더 많아지면 하위 폴더를 각각 만들어서 묶어서 관리해보세요.
- 디버깅 코드는 삭제하세요 (console.log) 에러처리를 개발자에게 알려주는 목적이라면 console.error()사용
- 전체적으로 컴포넌트 들이 크기가 작아서 좋네요.

화이팅~

**Comment by jun-min1623** [comment]
아앗 리뷰 달아주신것 이제 확인하였습니다 ! 정말 감사합니다!
해당 사항들 처리해 보겠습니다!
